install: true
language: android
android:
  components:
  - platform-tools
  - build-tools-26.0.1
  - android-26
      # Additional components
     - extra-google-google_play_services
     - extra-google-m2repository
     - extra-android-m2repository
     - addon-google_apis-google-26

before_script:
   - npm install
script:
- "./gradlew testDebugUnitTest"
- "./gradlew assembleRelease"
after_script:
- curl -u "slavromanov1:WkwqGwu9oSSqHgnkDPnq" -X POST "https://api.browserstack.com/app-automate/upload" -F "file=@./app/build/outputs/apk/release/app-release.apk"
before_install:
- chmod +x gradlew
- yes | sdkmanager "platforms;android-27"
before_cache:
- rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
- rm -rf $HOME/.gradle/caches/*/plugin-resolution/
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
  - "$HOME/.android/build-cache"
  - "node_modules"
addons:
  browserstack:
    username: "slavromanov1"
    access_key: "WkwqGwu9oSSqHgnkDPnq"